name: Terraform Deploy (LocalStack)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Iniciar LocalStack
        run: |
          docker run -d \
            --name localstack \
            -p 4566:4566 \
            -e SERVICES=s3 \
            -e DEBUG=1 \
            localstack/localstack


      - name: Esperar a LocalStack (health check)
        run: |
          sleep 10
          docker logs localstack

      - name: Ejecutar Terraform dentro de LocalStack
        run: |
          docker exec localstack sh -c "
            apk add --no-cache curl unzip &&
            curl -o terraform.zip https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip &&
            unzip terraform.zip &&
            mv terraform /usr/local/bin/ &&
            terraform init &&
            terraform plan &&
            terraform apply -auto-approve
 
          "

# fix final deploy
