name: Terraform Deploy (LocalStack)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Iniciar LocalStack
        run: |
          docker run -d \
            -p 4566:4566 \
            -e SERVICES=s3 \
            -e DEBUG=1 \
            localstack/localstack

      - name: Esperar a LocalStack (health check)
        run: |
          for i in {1..10}; do
            curl -s http://localhost:4566/health | grep '"s3": "running"' && break
            echo "Esperando LocalStack..."
            sleep 5
          done

      - name: Inicializar Terraform
        run: terraform init

      - name: Plan Terraform
        run: terraform plan

      - name: Apply Terraform
        run: terraform apply -auto-approve

# fix final deploy
